name = "pr-checker"
main = "src/index.js"
compatibility_date = "2024-01-30"
workers_dev = true

[version_metadata]
binding = "CF_VERSION"

[[kv_namespaces]]
binding = "PR_CACHE"
id = "625d347f211b47a6826004dda000b9a4"
preview_id = "5760d58693894fb99780fcfa049cb11f"

[[routes]]
pattern = "pr-check.control-j.com"
custom_domain = true

